### ISSUE TITLE
关于本项目一些不成熟的建议

### ISSUE THREAD

**Issue by skymkmk** [AHUer-LeapLap/Impart-Inherit#12]
我也是看了看随便打出来的，这里只是一些不成熟的建议，希望大佬们能参考参考。

1. 根据 [工信部域名行业管理信息公示](https://domain.miit.gov.cn)，.wiki 域名是可以进行备案的。但是由于域名中包含 AHU，不知道工信部那边会不会给过。不知道管理者们是否曾经考虑过这个问题，不过如果成功备案了，这个域名肯定比 Gitee Pages 的域名好看。
2. 翻看仓库记录发现曾经是尝试实现黑暗模式的，但是不知道为何在我的设备上并没有实现。如果可以的话，可以尝试把框架从 Docsify 迁移到 VitePress。VitePress 在黑暗模式这一点上可以说是开箱即用，而且相比 Docsify 来说更加美观。
3. 建议清理一下本仓库。本仓库工作区有一些本人认为可能无用的历史文档或代码，如果想要存档的话，可以活用 Git 的 tag 功能，给其打上标签，这样也方便回溯。

以上是本人的一些愚见，权当抛砖引玉。

**Comment by xiaohai99** [comment]
谢谢skymkmk大佬的指点！看得出你有很认真看仓库里的各个内容，深受鼓舞，我们辛苦做出来的东西还是有人在认真关注着的。

> 关于第一点和第二点，谢谢你提出这些建议。所见略同，这两点，在21年我搭建网站的初期也有考虑过，当时存在更多美观、设计、排版、访问速度上的问题，这两点算是当时留下来的硬骨头。我们会在有空的时候考虑优化这两点（如果科研十分顺利的话...)

> 关于第三点，不知道你说的具体有哪些。不过其中一些是我特地留下来给未来有心从www.ahu.wiki网站来到GitHub探索的朋友看的，从一些历史文档里面可以看出本项目曾经的样子、如今的发展，类似于“网页快照”。还有一些是留存下来，随着春夏秋冬的变化，可以快速进行修改切换对应的场景。

（长叹一声）在网站搭建初期我也是名技术派。但其实本项目目前最大的问题是运营人手不够（需要有更多人来找大家来写经验贴、更新内容），宣传力度不够（需要有更多人将本项目传播到每个需要的安大人耳中）。如果本项目的受众越来越少，再美丽的皮囊也会在岁月的长河中变成灰尘随风消散呀。

> 这种项目算是强运营的项目而不是强技术的项目。上述提到的这两方面问题也在安大的学长学姐曾经奋力做过经验传承类项目中发生过（如安大有戏团队的选课攻略、《安微大学信息安全专业入门指导》等）。

> 这两方面问题也一定程度上存在于其他高校的类似项目中：随着初创成员的毕业，项目渐渐失去维护，冷淡下来。

> 好在大学里从来不缺我们这样的人，每一代人都能想出新的点子，帮助后来者，并乐在其中，这何尝不是一种慰藉。如果你有想法的话，欢迎宣传/加入/主导本项目呀！

**Comment by classmatezhu** [comment]
1. 关于备案：服务器选在国内，访问速度会很快，但是因为是公益项目没有收入，我们没有财力支撑长期的服务器支出。不在国内架设服务器，就自然没有备案的需求。
2. 暗黑模式：Docsify不足的地方很多，如果以后有机会，我觉得换技术栈只是一个时间问题。

**Comment by skymkmk** [comment]
很高兴看到初创成员仍然为这个项目添砖加瓦，也十分感激各位学长 / 学姐能耐心看完我的建议。关于仓库内容的问题，听 @xiaohai99 讲完我才意识到我陷入了知识诅咒的陷阱。也希望这个项目能越来越好。

既然各位学长都看见了这些建议，我就先把这个 issue close 了。也希望各位学长学姐事业有成，学业顺利。
